# Generated by Django 4.2.1 on 2023-06-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='user_product_price',
        ),
    ]
